<template>
  <div>
    <div class="loadingio-spinner-ellipsis-ytsr6zs1n7m">
      <div class="ldio-3xz7x35t7v4">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
    <h1>Loading</h1>
    <div class="meter">
      <span style="width:100%;">
        <span class="progress"></span>
      </span>
    </div>
  </div>
</template>
<script>
export default { name: 'Loading' };
</script>

<style scoped>
@keyframes ldio-3xz7x35t7v4 {
  0% {
    transform: translate(15.24px, 101.6px) scale(0);
  }
  25% {
    transform: translate(15.24px, 101.6px) scale(0);
  }
  50% {
    transform: translate(15.24px, 101.6px) scale(1);
  }
  75% {
    transform: translate(101.6px, 101.6px) scale(1);
  }
  100% {
    transform: translate(187.96px, 101.6px) scale(1);
  }
}
@keyframes ldio-3xz7x35t7v4-r {
  0% {
    transform: translate(187.96px, 101.6px) scale(1);
  }
  100% {
    transform: translate(187.96px, 101.6px) scale(0);
  }
}
@keyframes ldio-3xz7x35t7v4-c {
  0% {
    background: #e15b64;
  }
  25% {
    background: #abbd81;
  }
  50% {
    background: #f8b26a;
  }
  75% {
    background: #f47e60;
  }
  100% {
    background: #e15b64;
  }
}
.ldio-3xz7x35t7v4 div {
  position: absolute;
  width: 50.8px;
  height: 50.8px;
  border-radius: 50%;
  transform: translate(101.6px, 101.6px) scale(1);
  background: #e15b64;
  animation: ldio-3xz7x35t7v4 1.923076923076923s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-3xz7x35t7v4 div:nth-child(1) {
  background: #f47e60;
  transform: translate(187.96px, 101.6px) scale(1);
  animation: ldio-3xz7x35t7v4-r 0.4807692307692307s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-3xz7x35t7v4-c 1.923076923076923s infinite step-start;
}
.ldio-3xz7x35t7v4 div:nth-child(2) {
  animation-delay: -0.4807692307692307s;
  background: #e15b64;
}
.ldio-3xz7x35t7v4 div:nth-child(3) {
  animation-delay: -0.9615384615384615s;
  background: #f47e60;
}
.ldio-3xz7x35t7v4 div:nth-child(4) {
  animation-delay: -1.4423076923076923s;
  background: #f8b26a;
}
.ldio-3xz7x35t7v4 div:nth-child(5) {
  animation-delay: -1.923076923076923s;
  background: #abbd81;
}
.loadingio-spinner-ellipsis-ytsr6zs1n7m {
  width: 254px;
  height: 254px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-3xz7x35t7v4 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-3xz7x35t7v4 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */

.meter {
  height: 5px;
  position: relative;
  background: #f3efe6;
  overflow: hidden;
}

.meter span {
  display: block;
  height: 100%;
}

.progress {
  background-color: #e4c465;
  -webkit-animation: progressBar 5s ease-in-out;
  -webkit-animation-fill-mode: both;
  -moz-animation: progressBar 5s ease-in-out;
  -moz-animation-fill-mode: both;
}

@-webkit-keyframes progressBar {
  0% {
    width: 0;
  }
  100% {
    width: 100%;
  }
}

@-moz-keyframes progressBar {
  0% {
    width: 0;
  }
  100% {
    width: 100%;
  }
}
h1 {
  color: cornflowerblue;
}
</style>